<?php

$arabic = array(
    //Navbar
    'nozha' => 'نزهة',
    'search' => 'ابحث....',
    'notifications' => 'الاشعارات',
    'messages' => 'الرسائل',
    'places' => 'الاماكن',
    'account' => 'الحساب',
    'profile' => 'البروفايل',
    'settings' => 'الاعدادات',
    'logout' => 'الخروج',

    //Profile
    'activity' => 'التفاعل',
    'about' => 'حول',
    'friends' => 'الاصدقاء',
    'nozhaplaces' => 'أماكن التنزة',
    'bio' => 'حول',
    'from' => 'من',
    'deletefriend' => 'احذف صديق',
    'acceptfriend' => 'اقبل الطلب',
    'addfriend' => 'اضف صديق',
    'cancelrequest' => 'احذف الطلب',

    //Places
    'places' => 'الاماكن',
    'whereareyou' => 'أين انت ؟',
    'allplaces' => 'كل الاماكن',
    'yourplaces' => 'اماكنك',
    'addplace' => 'أضف مكان',
    'city' => 'المدينة',
    'province' => 'المحافظة',
    'country' => 'الدولة',
    'go' => 'اذهب !',
    'cafe' => 'مقهى',
    'more' => 'المزيد',

    //Settings
    'edityourinfo' => 'تعديل البيانات',
    'editquote' => 'من هنا تستطيع تعديل كل بياناتك !',
    'basic' => 'اساسي',
    'firstname' => 'الاسم الاول',
    'fathername' => 'اسم الاب',
    'lastname' => 'الاسم الاخير',
    'email' => 'البريد الالكتروني',
    'additional' => 'اضافي',
    'phone' => 'الهاتف',
    'pictures' => 'صور',
    'profilepicture' => 'صورة الحساب',
    'coverpicture' => 'صورة الغلاف',
    'password' => 'كلمة السر',
    'confirmpassword' => 'تأكيد كلمة السر',
    'edit' => 'تعديل',

    //Notifiactions
    'invites' => 'الدعوات',
    'friendrequests' => 'طلبات الصداقة',

    //Feed
    'posts' => 'المنشورات',
    'friends' => 'الاصدقاء',
    'placesforyou' => 'أماكن مقترحة',
    'visit' => 'زيارة',
    'writeapost' => 'اكتب منشور',
    'writepostquote' => 'أين تريد ان تذهب ؟',
    'post' => 'انشر',
    'like' => 'اعجاب',
    'liked' => 'اعجبك',
    'comment' => 'تعليق',
    'leavecomment' => 'اترك تعليق .....',
    'write' => 'اكتب',
    'getposts' => 'المزيد',
    'goforwalk' => 'اذهب للتمشي',
    'whotofollow' => 'أصدقاء مقترحون',
    'addfriend' => 'أضف صديق',
    'nozha2018' => 'نزهة 2018 &copy;',
    'privacypolicy' => 'سياسة الخصوصية',
    'about' => 'حول',
    'help' => 'مساعدة',

    //Index
    'welcometo' => 'أهلا بكم في',
    'welcomequote' => 'اذا كانت تلك زيارتك الأولى لنا فسنكون سعداء اذا قمت بالتسجيل ان لم تكن فقم بتسجيل الدخول',
    'login' => 'تسجيل الدخول',
    'loginquote' => 'ادخل اسم المستخدم وكلمة السر',
    'username' => 'اسم المستخدم',
    'usernotfound' => 'المستخدم غير موجود',
    'signup' => 'انشاء حساب',
    'signupquote' => 'سنكون سعداء بوجودك معنا',
    'signmeup' => 'سجل الأن',
    'loginnow' => 'سجل الدخول الأن',

    //Add place
    'addplace' => 'اضف مكان',
    'name' => 'الاسم',
    'namequote' => 'ادخل اسم المكان',
    'description' => 'الوصف',
    'descriptionquote' => 'اوصف المكان بدقة',
    'budget' => 'الميزانية',
    'budgetquote' => 'ادخل متوسط الاسعار',
    'plan' => 'الخطة',
    'planquote' => 'ماذا يمكنني ان افعل هناك ؟',
    'address' => 'العنوان',
    'addressquote' => 'ادخل عنوان المكان',
    'cityquote' => 'ادخل المدينة',
    'provincequote' => 'ادخل المحافظة',
    'countryquote' => 'ادخل الدولة',
    'placetype' => 'نوع المكان',
    'cafe' => 'مقهى',
    'restaurant' => 'مطعم',
    'club' => 'نادي',
    'finish' => 'انهاء',

    //place
    'gallery' => 'الصور',
    'whattodo' => 'ماذا تفعل',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',

);

$english = array(
    //Navbar
    'nozha' => 'Nozha',
    'search' => 'Search .....',
    'notifications' => 'Notifications',
    'messages' => 'Messages',
    'places' => 'Places',
    'account' => 'Account',
    'profile' => 'Profile',
    'settings' => 'Settings',
    'logout' => 'Logout',

    //Profile
    'activity' => 'Activity',
    'about' => 'About',
    'friends' => 'Friends',
    'nozhaplaces' => 'Nozha places',
    'bio' => 'Bio',
    'from' => 'From',
    'deletefriend' => 'Delete friend',
    'acceptfriend' => 'Accept friend',
    'addfriend' => 'Add friend',
    'cancelrequest' => 'Cancel request',

    //Places
    'places' => 'Places',
    'whereareyou' => 'Where are you ?',
    'allplaces' => 'All places',
    'yourplaces' => 'Your places',
    'addplace' => 'Add place',
    'city' => 'City',
    'province' => 'Province',
    'country' => 'Country',
    'go' => 'Go !',
    'cafe' => 'Cafe',
    'more' => 'More',

    //Settings
    'edityourinfo' => 'Edit your info',
    'editquote' => 'From here you can edit all your information',
    'basic' => 'Basic',
    'firstname' => 'Firstname',
    'fathername' => 'Fathername',
    'lastname' => 'Lastname',
    'email' => 'Email',
    'additional' => 'Additional',
    'phone' => 'Phone',
    'pictures' => 'Pictures',
    'profilepicture' => 'Profile picture',
    'coverpicture' => 'Cover picture',
    'password' => 'Password',
    'confirmpassword' => 'Confirm password',
    'edit' => 'Edit',

    //Notifiactions
    'invites' => 'Invites',
    'friendrequests' => 'Friend requests',

    //Feed
    'posts' => 'Posts',
    'friends' => 'Friends',
    'placesforyou' => 'Places for you',
    'visit' => 'Visit',
    'writeapost' => 'write post',
    'writepostquote' => 'Where do you want to go ?',
    'post' => 'Post',
    'like' => 'Like',
    'liked' => 'Liked',
    'comment' => 'Comment',
    'leavecomment' => 'Leave comment .....',
    'write' => 'Write',
    'getposts' => 'More',
    'goforwalk' => 'Go for walk',
    'whotofollow' => 'Who to follow',
    'addfriend' => 'Add friend',
    'nozha2018' => 'Nozha 2018 &copy;',
    'privacypolicy' => 'Privacy policy',
    'about' => 'About',
    'help' => 'Help',

    //Index
    'welcometo' => 'Welocme to',
    'welcomequote' => 'If this is you first visit so please register, if not login',
    'login' => 'Login',
    'loginquote' => 'Enter username and password',
    'username' => 'Username',
    'usernotfound' => 'User not found',
    'signup' => 'Sign up',
    'signupquote' => 'We will be happy to be with you',
    'signmeup' => 'Sign me up',
    'loginnow' => 'Login now',
    '' => '',
    '' => '',
);